---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Set up RGBDS"
        run: |
          git clone https://github.com/gbdev/rgbds.git
          cd rgbds
          make
          sudo make install
          cd ..
      - name: "Build"
        run: make
      - uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: TixTest-GB.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: TixTest-GB.zip
